# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - lexatlas-frontend

on:
  push:
    branches:
      - chainlit
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      # - name: Zip artifact for deployment
      #   run: zip release.zip ./* -r
      - name: Zip artifact for deployment
        run: |
          zip release.zip ./* -r \
            -x "Dockerfile" \
            -x "docker-compose.yml" \
            -x "db/*" \
            -x "infra/*" \
            -x "init/*" \
            -x "tools/*" \
            -x ".github/*" \
            -x "README.md" \
            -x "chainlit.md" \
            -x ".gitignore" \
            -x "test.py"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
                
      - name: Create .env file from GitHub Secrets
        run: |
          echo "LITERAL_API_KEY=${{ secrets.LITERAL_API_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "CHAINLIT_AUTH_SECRET=${{ secrets.CHAINLIT_AUTH_SECRET }}" >> .env
 
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'lexatlas-frontend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8E6A4A7D56814F6BBCDC7433D4C1DB1A }}